import { useState } from 'react';
import { Link } from 'react-router-dom';
import { MessageSquare, ShoppingBag, Wallet, Timer, ArrowUpRight, ArrowRight, ShieldCheck, ChevronRight, Sparkles, Check, Package, CheckCheck } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '../ui/dialog';
import { useStore } from '../../lib/store';
import { money } from '../../lib/demoData';
import { Avatar, Badge, OrderDialog } from './Shared';

export const Metrics = ({ period }) => {
  const metrics = [
    { id: 'chats', icon: MessageSquare, name: 'Percakapan masuk', value: period === '7' ? '486' : '1.820', change: '18,6%', color: 'blue', points: '0,28 10,23 19,26 29,16 40,20 51,11 60,14 73,3' },
    { id: 'orders', icon: ShoppingBag, name: 'Pesanan dibuat', value: period === '7' ? '168' : '558', change: '12,5%', color: 'mint', points: '0,27 11,22 22,25 32,14 42,18 52,8 63,10 73,1' },
    { id: 'revenue', icon: Wallet, name: 'Total penjualan', value: period === '7' ? 'Rp12.450.000' : 'Rp41.680.000', change: '24,8%', color: 'blue', points: '0,28 10,24 20,27 30,15 40,19 50,8 61,12 73,2' },
    { id: 'response', icon: Timer, name: 'Rata-rata respons', value: '3,2', unit: 'detik', change: '82% lebih cepat', color: 'peach', points: '0,3 12,8 22,6 31,17 43,15 53,25 63,22 73,28' },
  ];
  return <div className="metrics-grid">{metrics.map(({ id, icon: Icon, name, value, unit, change, color, points }) => <section className="metric-card" key={id}><div className="metric-top"><span data-testid={`metric-${id}-label`}>{name}</span><span className={`metric-icon ${color}`}><Icon size={18} strokeWidth={1.7} /></span></div><div className="metric-middle"><strong data-testid={`metric-${id}-value`}>{value}{unit && <small>{unit}</small>}</strong><svg className={`sparkline ${color}`} viewBox="0 0 76 32" aria-hidden="true"><polyline points={points} fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" /></svg></div><div className="metric-bottom" data-testid={`metric-${id}-change`}><span><ArrowUpRight size={12} />{change}</span>{id !== 'response' && <small>vs {period === '7' ? 'minggu' : 'bulan'} lalu</small>}{id === 'response' && <small>dari manual</small>}</div></section>)}</div>;
};
export const Approvals = () => {
  const { orders, products } = useStore(); const [selected, setSelected] = useState(null);
  const pending = orders.filter(o => o.status === 'Menunggu persetujuan');
  return <section className="panel approvals-panel"><div className="panel-heading"><div className="approval-title"><span className="approval-icon"><ShieldCheck size={19} /></span><h2 data-testid="approvals-title">Perlu persetujuan</h2></div><span className="count-badge" data-testid="approval-count">{pending.length}</span></div><p className="panel-description" data-testid="approvals-description">Asisten sudah siapkan. Tinggal Anda putuskan.</p><div className="approval-list">{pending.length ? pending.slice(0, 3).map(o => <div className="approval-item" key={o.id}><div className="approval-person"><Avatar name={o.name} color={o.id === 'T-1048' ? 'peach' : o.id === 'T-1047' ? 'blue' : 'pink'} small /><div><strong data-testid={`approval-name-${o.id}`}>{o.name}</strong><span data-testid={`approval-time-${o.id}`}>#{o.id} · {o.time}</span></div><span className="pending-dot" /></div><div className="approval-product" data-testid={`approval-product-${o.id}`}>{o.qty} × {products.find(p => p.id === o.product)?.name}<strong>{money(o.qty * o.price + o.shipping)}</strong></div><button className="review-button" data-testid={`review-order-${o.id}`} onClick={() => setSelected(o.id)}>Tinjau pesanan<ArrowRight size={14} /></button></div>) : <div className="all-clear" data-testid="all-orders-approved"><span><CheckCheck size={34} /></span><strong>Semua sudah tuntas!</strong><p>Tidak ada pesanan yang menunggu persetujuan.</p></div>}</div><Link className="panel-bottom-link" to="/pesanan" data-testid="all-approvals-link">Lihat semua pesanan<ChevronRight size={14} /></Link><OrderDialog id={selected} onClose={() => setSelected(null)} /></section>;
};
export const RecentChats = () => {
  const { chats } = useStore();
  return <section className="panel recent-chats"><div className="panel-heading"><h2 data-testid="recent-chats-heading">Percakapan terbaru</h2><Link to="/percakapan" className="text-link" data-testid="all-chats-link">Lihat semua<ArrowUpRight size={14} /></Link></div><div className="conversation-table"><div className="conversation-table-head"><span>Pelanggan</span><span>Status</span><span>Waktu</span><span /></div>{chats.slice(0, 4).map(c => <Link to={`/percakapan?chat=${c.id}`} className="conversation-row" key={c.id} data-testid={`recent-chat-${c.id}`}><div className="customer-cell"><Avatar name={c.name} color={c.color} small /><div><strong>{c.name}</strong><p>{c.preview}</p></div></div><Badge status={c.status} id={`recent-chat-status-${c.id}`} /><span className="conversation-time">{c.time}</span><ChevronRight size={15} /></Link>)}</div><div className="channel-footnote"><span className="whatsapp-mini"><MessageSquare size={12} /></span>WhatsApp Business<span className="channel-line" />Percakapan dari semua pelanggan Anda</div></section>;
};
export const Activity = () => {
  const { activity, settings } = useStore(); const [open, setOpen] = useState(false);
  const icons = { order: ShoppingBag, chat: MessageSquare, stock: Package, done: Check };
  const list = (items, prefix) => <div className="activity-list">{items.map(a => { const Icon = icons[a.kind] || Check; return <div className="activity-item" key={a.id} data-testid={`${prefix}-${a.id}`}><span className={`activity-icon ${a.kind}`}><Icon size={14} /></span><div><strong>{a.text}</strong><p>{a.detail}</p><small>{a.time}</small></div></div>; })}</div>;
  return <section className="panel activity-panel"><div className="panel-heading"><h2 data-testid="activity-heading"><Sparkles size={17} />Aktivitas asisten</h2><span className={`online-badge ${!settings.assistant ? 'inactive' : ''}`} data-testid="assistant-status"><i />{settings.assistant ? 'Aktif' : 'Dijeda'}</span></div>{list(activity.slice(0, 3), 'activity')}<button className="panel-bottom-link" data-testid="all-activity-button" onClick={() => setOpen(true)}>Lihat semua aktivitas<ChevronRight size={14} /></button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="app-modal activity-modal" data-testid="activity-dialog"><DialogTitle data-testid="activity-dialog-title">Aktivitas asisten</DialogTitle><DialogDescription data-testid="activity-dialog-description">Jejak aktivitas dan keputusan bisnis Anda.</DialogDescription>{list(activity, 'full-activity')}</DialogContent></Dialog></section>;
};