import { useState } from 'react';
import { ArrowUpRight, MessageSquare, PackageSearch, ClipboardList, Check, CheckCheck, ShieldCheck, Sparkles, ArrowRight, MessageCircle, CircleCheck, MousePointer2 } from 'lucide-react';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '../ui/accordion';
import { Chapter, Reveal, ActionButton } from './Common';

const pains = [
  { icon: MessageSquare, title: 'Chat menumpuk.', text: 'Pelanggan menunggu jawaban. Anda masih sibuk mengurus pesanan lainnya.', result: 'Respons cepat, peluang tetap dekat.' },
  { icon: PackageSearch, title: 'Stok bikin ragu.', text: 'Bolak-balik cek varian dan stok. Salah sedikit, pesanan bisa berantakan.', result: 'Cek data dulu, bukan asal jawab.' },
  { icon: ClipboardList, title: 'Order terselip.', text: 'Detail pesanan tercecer di percakapan. Rekap manual memakan waktu dan tenaga.', result: 'Percakapan jadi draft pesanan rapi.' },
];
export const Manifesto = () => <section className="manifesto wrap section-space" id="solusi">
  <Reveal><Chapter number="01">MASALAH NYATA. SOLUSI YANG BEKERJA.</Chapter></Reveal>
  <Reveal className="section-heading-row"><h2 className="display-heading" data-testid="problem-heading">Usaha Anda butuh asisten.<br /><span className="muted-heading">Bukan sekadar balasan.</span></h2><p data-testid="problem-intro">Anda bukan kekurangan semangat.<br />Anda hanya punya dua tangan.<br />Saatnya punya bantuan yang benar-benar bekerja.</p></Reveal>
  <div className="pain-grid">{pains.map(({ icon: Icon, title, text, result }, i) => <Reveal className="pain-item" key={title} delay={i * 0.1}><div className="pain-top"><span className={`pain-icon pain-icon-${i}`}><Icon size={23} strokeWidth={1.6} /></span><span className="item-index">/ 0{i + 1}</span></div><h3 data-testid={`pain-title-${i}`}>{title}</h3><p data-testid={`pain-description-${i}`}>{text}</p><div className="pain-result" data-testid={`pain-result-${i}`}><ArrowUpRight size={16} />{result}</div></Reveal>)}</div>
</section>;

const stages = [
  { title: 'Pelanggan chat seperti biasa', short: 'Chat diterima', description: 'Tidak perlu mengubah kebiasaan pelanggan. Mulai dari percakapan sehari-hari.', icon: MessageCircle },
  { title: 'Tuntas cek, bukan menebak', short: 'Data diperiksa', description: 'Kebutuhan dibaca, stok dan varian diperiksa sebelum pesanan disiapkan.', icon: PackageSearch },
  { title: 'Draft pesanan siap ditinjau', short: 'Draft disiapkan', description: 'Produk, jumlah, alamat, dan ongkir tersusun dalam satu ringkasan yang jelas.', icon: ClipboardList },
  { title: 'Anda setuju. Baru jalan.', short: 'Anda menyetujui', description: 'Keputusan penting menunggu persetujuan Anda. Lebih ringan, tetap terkendali.', icon: ShieldCheck },
];
export const Workflow = ({ onDemo }) => {
  const [active, setActive] = useState(2);
  return <section className="workflow" id="cara-kerja"><div className="wrap section-space">
    <Reveal><Chapter number="02" light>DARI CHAT SAMPAI TUNTAS</Chapter></Reveal>
    <div className="workflow-grid"><Reveal className="workflow-copy"><h2 className="display-heading" data-testid="workflow-heading">Asisten mengerjakan.<br /><span>Anda memutuskan.</span></h2><p className="workflow-intro" data-testid="workflow-intro">Satu alur yang rapi. Tanpa bolak-balik aplikasi.<br />Tanpa kehilangan kendali atas bisnis sendiri.</p><div className="workflow-stages" role="tablist" aria-label="Tahapan cara kerja">{stages.map((stage, i) => <button role="tab" aria-selected={i === active} aria-controls="workflow-panel" id={`stage-tab-${i}`} key={stage.title} className={`stage-button ${active === i ? 'is-active' : ''}`} data-testid={`workflow-stage-${i}`} onClick={() => setActive(i)}><span className="stage-number">0{i + 1}</span><span>{stage.title}</span><ArrowUpRight size={17} /></button>)}</div></Reveal>
      <Reveal className="workflow-preview" delay={0.15}><div className="product-window"><div className="window-chrome"><div className="window-dots"><i /><i /><i /></div><span data-testid="product-demo-label">TUNTAS / RUANG KERJA ANDA</span><span className="simulation-pill">SIMULASI</span></div><div className="product-body"><div className="product-title"><div><small data-testid="product-date">SELAMAT PAGI, PEMILIK USAHA</small><h3 data-testid="product-heading">Satu chat. Banyak yang beres.</h3></div><span className="workspace-avatar">TU</span></div><div className="incoming-chat"><div className="customer-avatar">D</div><div><strong data-testid="workspace-customer">Dina · Pelanggan</strong><p data-testid="workspace-message">Kak, mau tote bag sage 2 pcs.<br />Kirim ke Bandung, ya!</p></div><span>09.41</span></div><div className="assistant-response"><span className="assistant-label" data-testid="workspace-assistant"><Sparkles size={14} />TUNTAS ASISTEN</span><div className="checks-list" data-testid="workspace-checks"><span><CircleCheck size={14} />Varian sage ditemukan</span><span><CircleCheck size={14} />Stok cukup untuk 2 pcs</span><span><CircleCheck size={14} />Ongkir Bandung dihitung</span></div></div><div className={`draft-order ${active >= 2 ? 'draft-highlight' : ''}`}><div className="draft-header"><strong data-testid="workspace-draft-title">Draft pesanan #T-001</strong><span data-testid="workspace-draft-status">Menunggu Anda</span></div><div className="draft-item" data-testid="workspace-item"><span className="product-icon"><ShoppingBagIcon /></span><span><strong>Tote Bag Everyday</strong><small>Sage · 2 pcs</small></span><strong>Rp150.000</strong></div><div className="draft-total" data-testid="workspace-total"><span>Total + ongkir</span><strong>Rp168.000</strong></div><button className="workspace-approval" data-testid="workspace-try-demo" onClick={onDemo}><CheckCheck size={16} />Coba setujui pesanan<ArrowRight size={15} /></button></div><p className="product-footnote" data-testid="workspace-sample-note"><ShieldCheck size={12} />Data contoh. Tidak ada transaksi sungguhan.</p></div></div><div id="workflow-panel" className="stage-description" role="tabpanel" aria-labelledby={`stage-tab-${active}`} data-testid="workflow-stage-description"><span>0{active + 1}</span><p key={active}>{stages[active].description}</p></div></Reveal>
    </div>
  </div></section>;
};

const ShoppingBagIcon = () => <svg viewBox="0 0 40 44" width="31" height="35" aria-hidden="true"><path d="M8 12h24l3 29H5z" fill="#a9bba8" /><path d="M14 15V9a6 6 0 0112 0v6" fill="none" stroke="#728870" strokeWidth="2" /><path d="M15 24h10M15 28h10" stroke="#dce5d8" strokeWidth="1.5" /></svg>;

export const Impact = () => <section id="dampak" className="impact wrap section-space">
  <Reveal><Chapter number="03">LEBIH RINGAN. LEBIH BANYAK PELUANG.</Chapter></Reveal>
  <Reveal className="impact-heading"><h2 className="display-heading" data-testid="impact-heading">Waktu Anda berharga.<br />Pakai untuk <span className="green-word">bertumbuh.</span></h2><div className="impact-symbol" aria-hidden="true">↗</div></Reveal>
  <div className="metrics-grid">{[{ value: '< 5', unit: 'detik', label: 'Target respons awal', text: 'Pelanggan tidak harus menunggu Anda selesai dengan urusan lain.' }, { value: '70', unit: '%', label: 'Target waktu admin dihemat', text: 'Kurangi pekerjaan berulang. Sisakan energi untuk ide besar berikutnya.' }, { value: '1', unit: 'klik', label: 'Persetujuan di tangan Anda', text: 'Asisten menyiapkan. Anda memeriksa dan memberi lampu hijau.' }].map((m, i) => <Reveal className="metric" key={m.label} delay={i * 0.1}><div className="metric-value" data-testid={`metric-value-${i}`}>{m.value}<span>{m.unit}</span></div><h3 data-testid={`metric-label-${i}`}>{m.label}</h3><p data-testid={`metric-description-${i}`}>{m.text}</p></Reveal>)}</div><p className="metric-disclaimer" data-testid="impact-disclaimer">*Angka merupakan target pengembangan berdasarkan PRD, bukan hasil penggunaan yang telah terverifikasi.</p>
  <Reveal className="control-banner"><span className="control-icon"><ShieldCheck size={30} strokeWidth={1.5} /></span><div><h3 data-testid="control-title">Otomatis bukan berarti lepas kendali.</h3><p data-testid="control-description">Dengan persetujuan pemilik, keputusan penting tetap menjadi milik Anda.</p></div><span className="control-badge" data-testid="control-badge"><span className="live-dot" />HUMAN IN THE LOOP</span></Reveal>
</section>;

const faqs = [
  ['Apa bedanya TuntasUMKM dengan chatbot biasa?', 'Chatbot biasa fokus menjawab pertanyaan. TuntasUMKM dirancang untuk membantu pekerjaan operasional: memeriksa stok, menghitung ongkir, dan menyiapkan draft pesanan. Tindakan penting tetap membutuhkan persetujuan Anda.'],
  ['Apakah asisten langsung menjalankan semua pesanan?', 'Tidak. Asisten menyiapkan ringkasan untuk ditinjau. Anda memeriksa detail dan memberi persetujuan sebelum pesanan diproses. Pendekatan ini disebut human-in-the-loop: manusia tetap memegang keputusan.'],
  ['Usaha seperti apa yang cocok menggunakan TuntasUMKM?', 'Konsep ini ditujukan untuk UMKM yang menerima banyak pertanyaan dan pesanan melalui percakapan, seperti toko fesyen, aksesori, produk rumahan, dan usaha ritel dengan produk serta stok yang jelas.'],
  ['Apakah demo ini terhubung ke WhatsApp dan stok asli?', 'Belum. Halaman ini adalah pratinjau konsep produk. Semua percakapan, stok, ongkir, dan pesanan pada demo merupakan data contoh yang berjalan lokal di browser. Tidak ada pesan yang dikirim atau transaksi yang dibuat.'],
  ['Apakah TuntasUMKM sudah bisa digunakan untuk bisnis saya?', 'TuntasUMKM masih dalam tahap pengembangan konsep. Anda dapat mencoba simulasi alur untuk memahami cara kerjanya. Jadwal ketersediaan dan harga layanan belum diumumkan.'],
];
export const FAQ = () => <section id="faq" className="faq-section"><div className="wrap faq-grid section-space"><Reveal><Chapter number="04">BIAR MAKIN JELAS</Chapter><h2 className="display-heading" data-testid="faq-heading">Masih ada<br />pertanyaan?</h2><p className="faq-intro" data-testid="faq-intro">Kenali dulu asisten baru<br />untuk usaha Anda.</p><span className="faq-decoration" aria-hidden="true"><MessageCircle size={75} strokeWidth={1} /><span>?</span></span></Reveal><Reveal className="faq-list" delay={0.12}><Accordion type="single" collapsible>{faqs.map(([q, a], i) => <AccordionItem value={`faq-${i}`} key={q}><AccordionTrigger data-testid={`faq-question-${i}`} className="faq-question"><span className="faq-number">0{i + 1}</span>{q}</AccordionTrigger><AccordionContent className="faq-answer" data-testid={`faq-answer-${i}`}>{a}</AccordionContent></AccordionItem>)}</Accordion></Reveal></div></section>;

export const Closing = ({ onDemo }) => <section className="closing"><div className="closing-grid-pattern" aria-hidden="true" /><Reveal className="wrap closing-content"><div className="eyebrow closing-eyebrow" data-testid="closing-eyebrow"><span className="live-dot" />RUANG LEBIH BESAR UNTUK USAHA ANDA</div><h2 data-testid="closing-heading">Anda bangun mimpinya.<br /><span>Kita tuntaskan sisanya.</span></h2><p data-testid="closing-description">Mulai dari satu percakapan. Lihat bagaimana Tuntas<br className="desktop-break" /> membantu mengubahnya jadi langkah nyata.</p><ActionButton onClick={onDemo} className="closing-button" testId="closing-demo">Coba alurnya sekarang</ActionButton><span className="closing-note" data-testid="closing-note"><MousePointer2 size={13} />Demo interaktif · Tanpa daftar</span><div className="closing-seal" aria-hidden="true"><Check size={75} strokeWidth={1.7} /></div></Reveal></section>;